{% set version = "9.0.0_asp" %}

package:
    name: isis
    version: {{ version }}

source:
  git_url: 'https://github.com/DOI-USGS/ISIS3.git'
  git_tag: 9.0.0

build:
    number: 0

requirements:
    build:
        - ale =0.11.0,<1
        - aom
        - armadillo
        - boost >=1.76.0,<1.82
        - boost-cpp >=1.76.0,<1.82
        - blas
        - bullet >=3.25
        - bz2file
        - bzip2
        - cmake >=3.27,<3.28
        - cspice =67
        - csm >=3.0.3,<3.0.4
        - curl >=8.4.0,<8.5
        - cxx-compiler=1.7
        - doxygen
        - eigen >=3, <4
        - embree >=3, <4
        - ffmpeg
        - geos >=3.12,<3.13
        - geotiff
        - gdal >=3.7,<3.9
        - gmp
        - gcovr
        - graphviz
        - conda-forge::gsl >=2.6, <2.7
        - hdf5
        - highfive
        - icu
        - usgs-astrogeology::inja
        - jama
        - kalasiris
        - krb5
        - libgdal >=3.7,<3.9
        - libopencv >=4.5,<4.10
        - libpng >=1.6.34,<1.7
        - libprotobuf >=4,<5
        - libtiff >=4.5,<4.8
        - libxml2
        - make
        - mesalib
        - mysql
        - nanoflann>=1.4.2,<1.5
        - nlohmann_json=3.11.2
        - ninja >=1.10,<1.11
        - nn
        - opencv >=4.5,<4.10
        - openssl >=3.1.2,<3.5
        - pcl >=1.13,<1.14
        - pdal=2.6
        - plio=1.5.3
        - protobuf >=4,<5
        - python >=3.9
        - python_abi >=3.9
        - pytest
        - rclone
        - qhull
        - qt-main>=5.15, <5.16
        - qwt <6.3.0
        - spiceql =1.2.0
        - sqlite >=3.46.0,<3.47
        - suitesparse <7.7.0
        - superlu
        - swig
        - texlive-core
        - tnt
        - usgscsm
        - x264
        - usgs-astrogeology::xalan-c
        - xerces-c >=3.2.4,<3.3.0a0
        - xorg-kbproto
        - xorg-libice
        - xorg-libsm
        - xorg-libx11
        - xorg-libxi
        - zlib >=1.3,<1.4.0a0

    run:
        - ale =0.11.0,<1
        - aom
        - armadillo
        - boost >=1.76.0,<1.82
        - boost-cpp >=1.76.0,<1.82
        - blas
        - bullet >=3.25
        - bz2file
        - bzip2
        - cmake >=3.27,<3.28
        - cspice =67
        - csm >=3.0.3,<3.0.4
        - curl >=8.4.0,<8.5
        - cxx-compiler=1.7
        - doxygen
        - eigen >=3, <4
        - embree >=3, <4
        - ffmpeg
        - geos >=3.12,<3.13
        - geotiff
        - gdal >=3.7,<3.9
        - gmp
        - gcovr
        - graphviz
        - conda-forge::gsl >=2.6, <2.7
        - hdf5
        - highfive
        - icu
        - usgs-astrogeology::inja
        - jama
        - kalasiris
        - krb5
        - libgdal >=3.7,<3.9
        - libopencv >=4.5,<4.10
        - libpng >=1.6.34,<1.7
        - libprotobuf >=4,<5
        - libtiff >=4.5,<4.8
        - libxml2
        - make
        - mesalib
        - mysql
        - nanoflann>=1.4.2,<1.5
        - nlohmann_json=3.11.2
        - ninja >=1.10,<1.11
        - nn
        - opencv >=4.5,<4.10
        - openssl >=3.1.2,<3.5
        - pcl >=1.13,<1.14
        - pdal=2.6
        - plio=1.5.3
        - protobuf >=4,<5
        - python >=3.9
        - python_abi >=3.9
        - pytest
        - rclone
        - qhull
        - qt-main>=5.15, <5.16
        - qwt <6.3.0
        - spiceql =1.2.0
        - sqlite >=3.46.0,<3.47
        - suitesparse <7.7.0
        - superlu
        - swig
        - texlive-core
        - tnt
        - usgscsm
        - x264
        - usgs-astrogeology::xalan-c
        - xerces-c >=3.2.4,<3.3.0a0
        - xorg-kbproto
        - xorg-libice
        - xorg-libsm
        - xorg-libx11
        - xorg-libxi
        - zlib >=1.3,<1.4.0a0

test:
  commands:
    - test -e $PREFIX/lib/libisis${SHLIB_EXT}
    - test -e $PREFIX/include/isis/Isis.h
    - test -e $PREFIX/bin/isisimport
    - ISISROOT=$PREFIX isisimport -HELP

about:
  home: https://github.com/USGS-Astrogeology/ISIS3
  license: CC0-1.0
  license_file: LICENSE.md
  summary: "Unofficial ISIS build recipe for Mac Arm"

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
